---
dependencies: []

galaxy_info:
  author: 
  description: Java 
  company: ""
  license: ""
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
      - 6
      - 7
  galaxy_tags:
    - development
    - system
    - web
    - java
    - jdk
    - openjdk
    - oracle
